Apricot/Apricot.Web/Controllers/DepartmentController.cs
using Apricot.Data;
using Apricot.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Apricot.Data.Repositories;

namespace Apricot.Web.Controllers
{
    [Authorize(Roles="Admin")]
    public class DepartmentController : Controller
    {
        public ActionResult Index()
        {
            var Db = new ApricotContext();
            var departments = Db.Departments;
            return View(departments);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Department model)
        {
            if(ModelState.IsValid)
            {
                var Db = new ApricotContext();
                DepartmentRepository repo = new DepartmentRepository(Db);
                repo.AddDepartment(model);
                return RedirectToAction("Index");
            }

            //Something Went wrong, redisplay form
            return View(model);
        }

        public ActionResult Edit(Int64 id)
        {
            var Db = new ApricotContext();
            var dept = Db.Departments.First(d => d.Dept_ID == id);
            return View(dept);
        }

        [HttpPost]
        public ActionResult Edit(Department model)
        {
            if (ModelState.IsValid)
            {
                var Db = new ApricotContext();
                var department = Db.Departments.First(dept => dept.Dept_ID == model.Dept_ID);

                // Update the dept data:
                department.Dept_Name = model.Dept_Name;
                Db.Entry(department).State = System.Data.Entity.EntityState.Modified;
                Db.SaveChanges();

                return RedirectToAction("Index");
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }
    }
}

Apricot/Apricot.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Alchemy Apricot", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container-fluid body-content">
        <div class="row">
            <div class="col-md-3">
                @Html.Partial("_SidePanel")
            </div>
            <div class="col-md-9 container">
                @RenderBody()

                @*<hr />
                    <footer>
                        <p>&copy; @DateTime.Now.Year - Alchemy Inc.</p>
                    </footer>*@
            </div>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    
    <script>
    $(function () {
        $("[data-toggle='popover']").popover();
    });
    </script>
</body>
</html>

Apricot/Apricot.Web/Views/Shared/_SidePanel.cshtml
<div class="affix" id="sidebar" data-spy="affix">
    @if (User.IsInRole("Employee") && !User.IsInRole("Admin"))
    {
        <div class="row">
            <div class="col-md-12">
                <div class="list-group">
                    <a class="list-group-item active">Employee</a>
                    @Html.ActionLink("My Bills", "Index", "Employee", null, new { @class = "list-group-item" })
                    @Html.ActionLink("New Bill", "Create", "Employee", null, new { @class = "list-group-item" })
                    @Html.ActionLink("Notifications", "Notifications", "Employee", null, new { @class = "list-group-item" })
                </div>
            </div>
        </div>
    }

    @if (User.IsInRole("Manager") && !User.IsInRole("Admin"))
    {
        <div class="row">
            <div class="col-md-12">
                <div class="list-group">
                    <a class="list-group-item active">Manager</a>
                    @Html.ActionLink("Manage Bills", "Index", "Manager", null, new { @class = "list-group-item" })
                </div>
            </div>
        </div>
    }

    @if (User.IsInRole("Finance Manager") && !User.IsInRole("Admin"))
    {
        <div class="row">
            <div class="col-md-12">
                <div class="list-group">
                    <a class="list-group-item active">Finance Manager</a>
                    @Html.ActionLink("Manage Bills", "Index", "FManager", null, new { @class = "list-group-item" })
                </div>
            </div>
        </div>
    }

    @if (User.IsInRole("Admin"))
    {
        <div class="row">
            <div class="col-md-12">
                <div class="list-group">
                    @Html.ActionLink("Admin", "Index", "Dashboard", null, new { @class = "list-group-item active" })
                    @Html.ActionLink("Manage Users", "Index", "Account", null, new { @class = "list-group-item " })
                    @Html.ActionLink("Manage Department", "Index", "Department", null, new { @class = "list-group-item " })
                    @Html.ActionLink("Manage Employee", "Index", "ManageEmployee", null, new { @class = "list-group-item " })
                </div>
            </div>
        </div>
    }

</div>